name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v5.0.0
        with:
          cache: true
          version: 10

      - name: Install Dependencies
        run: pnpm install
      - name: Formatting
        run: pnpm run format --write
      - name: Linting
        run: pnpm run lint --write
      - name: Check
        run: pnpm run check --write

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.15.0
        with:
         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
